services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - /data/asap2/nginx_logs:/var/log/nginx
#       - /etc/pki/tls/certs/asap.epfl.ch.pem:/etc/nginx/asap.epfl.ch.pem
#       - /etc/pki/tls/private/asap.epfl.ch.key:/etc/nginx/asap.epfl.ch.key
#       - /etc/pki/tls/certs/asap-beta.epfl.ch.pem:/etc/nginx/asap-beta.epfl.ch.pem
#       - /etc/pki/tls/private/asap-beta.epfl.ch.key:/etc/nginx/asap-beta.epfl.ch.key
       - '/data/asap2/:/data/asap2'       
    links:
      - website
    ports:
      - 8080:8080
#      - 3000:3000
#      - 8181:8181
    restart: always    
    networks:
       - asap_network

  postgres:
    image: 'postgres:13-alpine'
    volumes:
      - '/data/asap2/pgsql-data:/var/lib/postgresql/data'
      - 'dumps:/dumps'
      - '/data/asap2/:/data/asap2'
      - /data/asap2/dumps_for_docker_init:/docker-entrypoint-initdb.d/
    command: -p 5434
    env_file:
      - '.env'
    ports:
      - '5433:5434'
    expose:
      - "5434"
    restart: always
    networks:
       - asap_network
#:
#        ipv4_address: 172.19.0.2

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'
    restart: always
    networks:
      - asap_network
#:
#       ipv4_address: 172.19.0.3

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    privileged: true
    group_add:
      - docker
#    user: root
    volumes:
      - '.:/app'
      - 'dumps:/dumps'
      - '/data/asap2/:/data/asap2'
      - '/mnt/asap-old:/mnt/asap-old'
      - '/srv/asap_run:/srv/asap_run'
      - '/srv/asap_run_new:/srv/asap_run_new'
      - '/var/run/docker.sock:/var/run/docker.sock'
    env_file:
      - '.env_website'
    restart: always
    networks:
       - asap_network


  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.env_website'
    restart: always
    networks:
      - asap_network
 #      ipv4_address: 172.19.0.5

  cable:
    depends_on:
      - 'redis'
    build: .
  #    command: puma --bind tcp://0.0.0.0:8181 cable/config.ru
    command: bundle exec puma -p 8181 cable/config.ru   
    ports:
      - '8081:8181'
    volumes:
      - '.:/app'
    env_file:
      - '.env_website'
    restart: always
    networks:
      - asap_network
#:
 #      ipv4_address: 172.19.0.6

networks:
   asap_network:
    driver: bridge
 #   driver_opts:
 #     com.docker.network.enable_ipv6: "false"
 #   ipam:
 #     driver: default
 #     config:
 #     - subnet: 172.19.0.0/24
 #       gateway: 172.19.0.1

volumes:
  dumps:
#  data:
  redis:
  postgres:
  
